version: '3.8'

services:
  resolver:
    # the name of the image to search for or the
    # name of the newly built image, if not found
    image: dns-resolver
    build:
      # docker build will run with the parent directory as the working directory
      context: ..
      dockerfile: docker/Dockerfile
    # mapping the local logs directory to the
    # container directory, in order to maintain access
    volumes:
      - ../logs:/dns/logs
    networks:
      res0:
        # a static IP address is necessary, to be able
        # to pass it as an argument to the python script
        ipv4_address: 10.100.100.2
    ports:
      # (127.0.0.1, 53) will be mapped to (10.100.100.1, 53) <- the default gateway of the container's network
      - "127.0.0.1:53:53/udp"
    # the desired root server can be changed here
    command: python resolver.py -i 10.100.100.2 -r 192.203.230.10 -b banned.txt -lb logs/banning-logs.json -lc logs/caching-logs.json

networks:
  res0:
    ipam:
      driver: default
      # change if it causes conflicts with a host interface
      config:
        - subnet: 10.100.100.0/24
          gateway: 10.100.100.1